from __future__ import annotations

import argparse
import csv
import io
from collections.abc import Mapping, Sequence
from pathlib import Path

from tools.e2e_models import (
    COMPONENT_IDS,
    DIMENSIONS_BY_ID,
    FLOW_ID,
    FLOW_STEPS,
    TARGET_CASES,
    TARGET_DIMENSIONS,
    E2eComponentVariant,
    E2eTargetCase,
    as_mapping,
    as_sequence,
    build_component_variants,
    component_actions,
    component_data_profiles,
    component_states,
    flow_document,
    load_component_yaml,
    markdown_escape,
    matrix_config,
    matrix_dimensions,
    parse_variant,
    scalar_text,
    string_list,
    target_title,
)
from tools.generation_io import check_outputs, write_outputs

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_e2e_case_list. "
    "Do not edit manually. -->"
)

ELEMENT_KIND_LABELS = {
    "invariant": "不変条件",
    "action": "操作",
    "state": "状態",
    "data": "データ",
}

OPERATION_TYPE_LABELS = {
    "command": "コマンド",
    "query": "参照",
    "side_effect": "副作用",
    "evidence": "証跡確認",
}


def component_variants_by_id() -> dict[str, E2eComponentVariant]:
    return {variant.variant_id: variant for variant in build_component_variants()}


def resolve_variant(
    variant_id: str,
    *,
    variants: Mapping[str, E2eComponentVariant],
) -> E2eComponentVariant:
    return variants.get(variant_id) or parse_variant(variant_id)


def dimension_targets_for_case(target_case: E2eTargetCase, dimension_id: str) -> list[str]:
    """ケースの対象を、matrix期待・goal variant・前提variantの順で解決する。"""
    row_dimension, column_dimension = matrix_dimensions()
    if target_case.matrix_assertions and dimension_id in (row_dimension, column_dimension):
        return sorted(
            {
                assertion.row_id if dimension_id == row_dimension else assertion.column_id
                for assertion in target_case.matrix_assertions
            }
        )
    goal = parse_variant(target_case.goal_variant)
    goal_target = goal.target(dimension_id)
    if goal_target is not None:
        return [goal_target]
    selected = [
        target_id
        for variant_id in target_case.selected_variants
        for target_id in [parse_variant(variant_id).target(dimension_id)]
        if target_id is not None
    ]
    return list(dict.fromkeys(selected))


def case_target_label(target_case: E2eTargetCase) -> str:
    labels = [
        " / ".join(target_title(target_id) for target_id in targets)
        for dimension in TARGET_DIMENSIONS
        for targets in [dimension_targets_for_case(target_case, dimension.dimension_id)]
        if targets
    ]
    return " x ".join(labels) if labels else "-"


def scenario_link(target_case: E2eTargetCase) -> str:
    return f"[詳細](cases/{target_case.filename})"


def flow_summary_for_variants(
    target_case: E2eTargetCase,
    *,
    variants: Mapping[str, E2eComponentVariant],
    titles: Mapping[str, Mapping[str, str]],
) -> str:
    actions: list[str] = []
    for variant_id in target_case.selected_variants:
        variant = resolve_variant(variant_id, variants=variants)
        action_title = title_only(
            variant.action_id,
            titles[variant.component_id].get(f"action:{variant.action_id}"),
        )
        if not actions or actions[-1] != action_title:
            actions.append(action_title)
    return " -> ".join(markdown_escape(action) for action in actions) if actions else "-"


def connective_action(action: str) -> str:
    if action.endswith("する"):
        return f"{action[:-2]}し"
    if action.endswith("す"):
        return f"{action[:-1]}し"
    return action


def matrix_evidence_label(target_case: E2eTargetCase) -> str:
    return "<br>".join(
        f"{target_title(assertion.column_id)} {assertion.expected}"
        for assertion in target_case.matrix_assertions
    )


def target_case_view(
    target_case: E2eTargetCase,
    *,
    variants: Mapping[str, E2eComponentVariant],
    titles: Mapping[str, Mapping[str, str]],
) -> tuple[str, str, str, str]:
    goal = resolve_variant(target_case.goal_variant, variants=variants)
    component_titles = titles[goal.component_id]
    action = title_only(goal.action_id, component_titles.get(f"action:{goal.action_id}"))
    state = title_only(goal.state_id, component_titles.get(f"state:{goal.state_id}"))
    data = concrete_data_label(goal)
    purpose = f"{case_target_label(target_case)}で{connective_action(action)}、{state}を確認する"
    evidence = matrix_evidence_label(target_case) or state
    return (
        markdown_escape(purpose),
        markdown_escape(data),
        markdown_escape(state),
        evidence,
    )


def render_component_case_summary(
    *,
    variants: Mapping[str, E2eComponentVariant],
    titles: Mapping[str, Mapping[str, str]],
) -> list[str]:
    lines = [
        "## 5. Component coverage summary",
        "",
        "| Component | 件数 | 代表ケース | 主な観点 |",
        "|---|---:|---|---|",
    ]
    for component_id in COMPONENT_IDS:
        component_cases = [
            target_case
            for target_case in TARGET_CASES
            if target_case.goal_component == component_id
        ]
        states: list[str] = []
        for target_case in component_cases:
            variant = resolve_variant(target_case.goal_variant, variants=variants)
            state = title_only(
                variant.state_id,
                titles[component_id].get(f"state:{variant.state_id}"),
            )
            if state not in states:
                states.append(state)
        representative = component_cases[0].case_id if component_cases else "-"
        lines.append(
            f"| `{component_id}` | {len(component_cases)} | `{representative}` | "
            f"{markdown_escape(', '.join(states) if states else '-')} |"
        )
    lines.append("")
    return lines


def matrix_heading() -> str:
    row_dimension, column_dimension = matrix_dimensions()
    return f"{DIMENSIONS_BY_ID[row_dimension].title} x {DIMENSIONS_BY_ID[column_dimension].title}"


def render_target_matrices(
    *,
    variants: Mapping[str, E2eComponentVariant],
    titles: Mapping[str, Mapping[str, str]],
) -> list[str]:
    row_dimension, column_dimension = matrix_dimensions()
    rows = DIMENSIONS_BY_ID[row_dimension]
    columns = DIMENSIONS_BY_ID[column_dimension]
    lines = [f"## 6. {matrix_heading()} matrix", ""]
    for component_id in string_list(matrix_config().get("components")):
        grouped: dict[str, dict[tuple[str, str], str]] = {}
        for target_case in TARGET_CASES:
            for variant_id in target_case.selected_variants:
                variant = resolve_variant(variant_id, variants=variants)
                if variant.component_id != component_id:
                    continue
                row_id = variant.target(row_dimension)
                column_id = variant.target(column_dimension)
                if row_id is None or column_id is None:
                    continue
                state = title_only(
                    variant.state_id,
                    titles[component_id].get(f"state:{variant.state_id}"),
                )
                data = title_only(
                    variant.data_id,
                    titles[component_id].get(f"data:{variant.data_id}"),
                )
                grouped.setdefault(f"{state} / {data}", {}).setdefault(
                    (row_id, column_id),
                    target_case.case_id,
                )
        if not grouped:
            continue
        component_title = titles[component_id].get("component", component_id)
        lines.extend([f"### {component_id} {component_title}", ""])
        header = " | ".join(target.title for target in columns.targets)
        separator = "|".join("---" for _ in range(len(columns.targets) + 1))
        for key, case_ids in grouped.items():
            lines.extend(
                [
                    f"#### {markdown_escape(key)}",
                    "",
                    f"| {rows.title} \\ {columns.title} | {header} |",
                    f"|{separator}|",
                ]
            )
            for row_target in rows.targets:
                row = [row_target.title]
                for column_target in columns.targets:
                    case_id = case_ids.get((row_target.target_id, column_target.target_id))
                    row.append(f"`{case_id}`" if case_id else "-")
                lines.append(f"| {' | '.join(row)} |")
            lines.append("")
    return lines


def render_generated_case_rows(
    *,
    variants: Mapping[str, E2eComponentVariant],
    titles: Mapping[str, Mapping[str, str]],
) -> list[str]:
    lines = ["## 7. Cases by component", ""]
    for component_id in COMPONENT_IDS:
        component_title = titles[component_id].get("component", component_id)
        lines.extend(
            [
                f"### {component_id} {component_title}",
                "",
                "| ID | 観点 | 対象 | データ | 処理概要 | 主なエビデンス | Link |",
                "|---|---|---|---|---|---|---|",
            ]
        )
        for target_case in TARGET_CASES:
            if target_case.goal_component != component_id:
                continue
            purpose, data, _state, evidence = target_case_view(
                target_case,
                variants=variants,
                titles=titles,
            )
            lines.append(
                f"| `{target_case.case_id}` | {purpose} | "
                f"{markdown_escape(case_target_label(target_case))} | {data} | "
                f"{flow_summary_for_variants(target_case, variants=variants, titles=titles)} | "
                f"{evidence} | {scenario_link(target_case)} |"
            )
        lines.append("")
    return lines


def render_variant_index_markdown() -> str:
    variants = component_variants_by_id()
    titles = component_element_titles()
    lines = [
        GENERATED_COMMENT,
        "",
        f"# {FLOW_ID} e2e variant index",
        "",
        "内部生成情報の確認用一覧。人間向けのケースレビューは "
        "[case-list_gen.md](case-list_gen.md) を参照する。",
        "",
        "| ケースID | Coverage Group | Goal Component | Goal Variant | "
        "Selected Variants | Matrix期待 | シナリオ |",
        "|---|---|---|---|---|---|---|",
    ]
    for target_case in TARGET_CASES:
        selected = "<br>".join(f"`{variant}`" for variant in target_case.selected_variants)
        assertions = (
            "<br>".join(
                f"`{assertion.row_id}` / `{assertion.column_id}`: `{assertion.expected}`"
                for assertion in target_case.matrix_assertions
            )
            if target_case.matrix_assertions
            else "-"
        )
        lines.append(
            f"| `{target_case.case_id}` | `{target_case.coverage_group}` | "
            f"`{target_case.goal_component}` | `{target_case.goal_variant}` | "
            f"{selected} | {assertions} | {scenario_link(target_case)} |"
        )
    lines.extend(["", "## 表示ラベル", ""])
    for component_id in COMPONENT_IDS:
        component_title = titles[component_id].get("component", component_id)
        lines.extend([f"### {component_id} {component_title}", ""])
        for variant in variants.values():
            if variant.component_id != component_id:
                continue
            data, action, state = variant_labels(variant, titles=titles)
            lines.append(f"- `{variant.variant_id}`: {data} / {action} / {state}")
        lines.append("")
    return "\n".join(lines)


def bool_text(value: object) -> str:
    if isinstance(value, bool):
        return "はい" if value else "いいえ"
    return "-"


def title_only(element_id: str | None, title: str | None = None) -> str:
    if element_id is None:
        return "-"
    return title or element_id


def data_profile(component_id: str, data_id: str) -> Mapping[str, object]:
    for profile in component_data_profiles(component_id):
        if profile.get("id") == data_id:
            return profile
    return {}


def concrete_data_label(variant: E2eComponentVariant) -> str:
    """variantの対象Targetとdata profileから、ケース一覧向けの具体データ名を返す。"""
    profile = data_profile(variant.component_id, variant.data_id)
    data_title = scalar_text(profile.get("title"), variant.data_id)
    target = " x ".join(target_title(target_id) for _dimension, target_id in variant.targets)
    if profile.get("label_mode") == "target":
        return target or data_title
    label = profile.get("label")
    if isinstance(label, str) and target:
        return f"{target} の{label}"
    return f"{target} / {data_title}" if target else data_title


def yaml_titles(items: Sequence[Mapping[str, object]]) -> dict[str, str]:
    return {
        scalar_text(item.get("id")): scalar_text(item.get("title"))
        for item in items
        if isinstance(item.get("id"), str)
    }


def component_element_titles() -> dict[str, dict[str, str]]:
    titles: dict[str, dict[str, str]] = {}
    for component_id in COMPONENT_IDS:
        component = as_mapping(
            load_component_yaml(component_id, "component.manual.yaml").get("component")
        )
        titles[component_id] = {
            "component": scalar_text(component.get("title")),
            **{
                f"action:{item_id}": title
                for item_id, title in yaml_titles(component_actions(component_id)).items()
            },
            **{
                f"state:{item_id}": title
                for item_id, title in yaml_titles(component_states(component_id)).items()
            },
            **{
                f"data:{item_id}": title
                for item_id, title in yaml_titles(component_data_profiles(component_id)).items()
            },
        }
    return titles


def variant_labels(
    variant: E2eComponentVariant,
    *,
    titles: Mapping[str, Mapping[str, str]],
) -> tuple[str, str, str]:
    component_titles = titles[variant.component_id]
    return (
        concrete_data_label(variant),
        title_only(variant.action_id, component_titles.get(f"action:{variant.action_id}")),
        title_only(variant.state_id, component_titles.get(f"state:{variant.state_id}")),
    )


def selected_variants_by_component(
    target_case: E2eTargetCase,
    *,
    variants: Mapping[str, E2eComponentVariant],
) -> dict[str, E2eComponentVariant]:
    selected: dict[str, E2eComponentVariant] = {}
    for variant_id in target_case.selected_variants:
        variant = resolve_variant(variant_id, variants=variants)
        selected[variant.component_id] = variant
    return selected


def render_coverage_summary(variants: Sequence[E2eComponentVariant]) -> list[str]:
    lines = [
        "## 2. Coverage summary",
        "",
        "| Component | Variants | Covered variants | Goal cases | Coverage |",
        "|---|---:|---:|---:|---:|",
    ]
    covered_variants = {
        variant_id for target_case in TARGET_CASES for variant_id in target_case.selected_variants
    }
    for component in COMPONENT_IDS:
        component_variants = [
            variant.variant_id for variant in variants if variant.component_id == component
        ]
        covered = [variant for variant in component_variants if variant in covered_variants]
        component_cases = [
            target_case for target_case in TARGET_CASES if target_case.goal_component == component
        ]
        coverage = (
            f"{len(covered) / len(component_variants) * 100:.1f}%" if component_variants else "-"
        )
        lines.append(
            f"| `{component}` | {len(component_variants)} | {len(covered)} | "
            f"{len(component_cases)} | {coverage} |"
        )
    lines.append("")
    return lines


def render_component_sections() -> list[str]:
    lines = ["## 3. コンポーネントごとの要素", ""]
    for component_id in COMPONENT_IDS:
        component_doc = load_component_yaml(component_id, "component.manual.yaml")
        component = as_mapping(component_doc.get("component"))
        lines.extend(
            [
                f"### {component_id} {scalar_text(component.get('title'))}",
                "",
                "| 種別 | ID | タイトル | 補足 |",
                "|---|---|---|---|",
            ]
        )
        for invariant in as_sequence(component_doc.get("business_invariants")):
            invariant_map = as_mapping(invariant)
            lines.append(
                f"| {ELEMENT_KIND_LABELS['invariant']} | "
                f"`{scalar_text(invariant_map.get('id'))}` | - | "
                f"{markdown_escape(scalar_text(invariant_map.get('text')))} |"
            )
        for action_map in component_actions(component_id):
            operation_type = scalar_text(action_map.get("operation_type"))
            detail = (
                f"操作種別={OPERATION_TYPE_LABELS.get(operation_type, operation_type)}, "
                f"既定状態={scalar_text(action_map.get('default_result'))}"
            )
            lines.append(
                f"| {ELEMENT_KIND_LABELS['action']} | "
                f"`{scalar_text(action_map.get('id'))}` | "
                f"{markdown_escape(scalar_text(action_map.get('title')))} | "
                f"{markdown_escape(detail)} |"
            )
        for state_map in component_states(component_id):
            detail = f"後続継続={bool_text(state_map.get('continue_flow'))}"
            lines.append(
                f"| {ELEMENT_KIND_LABELS['state']} | "
                f"`{scalar_text(state_map.get('id'))}` | "
                f"{markdown_escape(scalar_text(state_map.get('title')))} | {detail} |"
            )
        for data_map in component_data_profiles(component_id):
            display_title = scalar_text(
                data_map.get("display_title"), scalar_text(data_map.get("title"))
            )
            tags = ", ".join(string_list(data_map.get("tags")))
            lines.append(
                f"| {ELEMENT_KIND_LABELS['data']} | "
                f"`{scalar_text(data_map.get('id'))}` | "
                f"{markdown_escape(display_title)} | "
                f"{markdown_escape(tags or '-')} |"
            )
        lines.append("")
    return lines


def render_case_list_rules() -> list[str]:
    lines = [
        "## 4. 枝刈り規則",
        "",
        "| Rule ID | 条件 | 結果 | 理由 |",
        "|---|---|---|---|",
    ]
    for item in as_sequence(flow_document().get("case_list_rules")):
        rule = as_mapping(item)
        lines.append(
            f"| `{scalar_text(rule.get('id'))}` | {scalar_text(rule.get('condition'))} | "
            f"{scalar_text(rule.get('result'))} | {scalar_text(rule.get('reason'))} |"
        )
    lines.append("")
    return lines


def render_case_list_markdown() -> str:
    variants = component_variants_by_id()
    titles = component_element_titles()
    lines = [
        GENERATED_COMMENT,
        "",
        f"# {FLOW_ID} e2e case list",
        "",
        "## 0. 読み方",
        "",
        "- Component coverage: 各論理コンポーネントのvariant coverage。",
        f"- Matrix: {matrix_heading()} の組み合わせ確認。",
        "- 内部variant一覧は [case-variant-index_gen.md](case-variant-index_gen.md) を参照。",
        "",
        "## 1. 対象フロー",
        "",
        "| Step | Operation | Endpoint | Template |",
        "|---|---|---|---|",
    ]
    for step in FLOW_STEPS:
        lines.append(
            f"| `{step.step_id}` | `{step.operation}` | "
            f"`{markdown_escape(f'{step.method} {step.path}')}` | `{step.template}` |"
        )
    lines.extend(
        [
            "",
            *render_coverage_summary(tuple(variants.values())),
            *render_component_sections(),
            *render_case_list_rules(),
            *render_component_case_summary(variants=variants, titles=titles),
            *render_target_matrices(variants=variants, titles=titles),
            *render_generated_case_rows(variants=variants, titles=titles),
            "## 8. Appendix",
            "",
            "- 内部variant一覧: [case-variant-index_gen.md](case-variant-index_gen.md)",
            "- CSV: [pruned-cases_gen.csv](pruned-cases_gen.csv)",
            "",
        ]
    )
    return "\n".join(lines)


def render_pruned_cases_csv() -> str:
    output = io.StringIO()
    writer = csv.writer(output, lineterminator="\n")
    variants = component_variants_by_id()
    titles = component_element_titles()
    writer.writerow(
        [
            "case_id",
            *[
                f"{component_id}[{kind}]"
                for component_id in COMPONENT_IDS
                for kind in ("データ", "操作", "状態")
            ],
        ]
    )
    for target_case in TARGET_CASES:
        selected = selected_variants_by_component(target_case, variants=variants)
        component_columns: list[str] = []
        for component_id in COMPONENT_IDS:
            variant = selected.get(component_id)
            if variant is None:
                component_columns.extend(("-", "-", "-"))
                continue
            component_columns.extend(variant_labels(variant, titles=titles))
        writer.writerow([target_case.case_id, *component_columns])
    return output.getvalue()


def rendered_outputs(output_root: Path = Path("docs/spec/50.e2e")) -> Mapping[Path, str]:
    flow_root = output_root / FLOW_ID
    return {
        flow_root / "case-list_gen.md": render_case_list_markdown(),
        flow_root / "case-variant-index_gen.md": render_variant_index_markdown(),
        flow_root / "pruned-cases_gen.csv": render_pruned_cases_csv(),
    }


def generate(*, check: bool = False, output_root: Path = Path("docs/spec/50.e2e")) -> int:
    rendered = rendered_outputs(output_root)
    if check:
        return check_outputs(rendered)
    write_outputs(rendered)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
