from __future__ import annotations

import argparse
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import cast

from tools.e2e_models import (
    E2E_SPEC_ROOT,
    FLOW_ID,
    TARGET_CASES,
    TARGET_DIMENSIONS,
    E2eComponentVariant,
    E2eTargetCase,
    as_mapping,
    as_sequence,
    component_actions,
    component_data_profiles,
    component_states,
    flow_document,
    item_by_id,
    load_component_yaml,
    load_yaml,
    markdown_escape,
    matrix_config,
    matrix_expectation_label,
    parse_variant,
    scalar_text,
    string_list,
    string_set,
    target_defaults,
    target_title,
)
from tools.generation_io import check_outputs, write_outputs

GENERATED_COMMENT = (
    "<!-- This file is generated by uv run python -m tools.generate_e2e_scenarios. "
    "Do not edit manually. -->"
)
WHOLE_FLOW_LABEL = "フロー全体"


@dataclass(frozen=True)
class EvidenceDetail:
    title: str
    collector: str
    ok_condition: str
    save_as: str


@dataclass(frozen=True)
class ScenarioStepDetail:
    component_title: str
    action_title: str
    state_title: str
    data_label: str
    target_label: str
    operation_steps: tuple[str, ...]
    setting_rows: tuple[tuple[str, str], ...]
    failure_trigger: str
    procedure: str
    evidences: tuple[EvidenceDetail, ...]


def sentence_body(value: str) -> str:
    return value.rstrip("。.")


def unique_texts(values: Sequence[str]) -> tuple[str, ...]:
    return tuple(dict.fromkeys(values))


def render_target_prerequisites() -> list[str]:
    prerequisites = string_list(flow_document().get("case_prerequisites"))
    return [f"{index}. {text}" for index, text in enumerate(prerequisites, start=1)]


def render_target_matrix_assertions(target_case: E2eTargetCase) -> list[str]:
    assertion_config = as_mapping(matrix_config().get("assertion"))
    if not target_case.matrix_assertions:
        return [scalar_text(assertion_config.get("none"))]
    lines = [scalar_text(assertion_config.get("heading"))]
    sentence = scalar_text(assertion_config.get("sentence"))
    for assertion in target_case.matrix_assertions:
        lines.append(
            "- "
            + sentence.replace("${row.title}", target_title(assertion.row_id))
            .replace("${column.title}", target_title(assertion.column_id))
            .replace("${expected}", matrix_expectation_label(assertion.expected))
        )
    return lines


def component_title(component_id: str) -> str:
    component = as_mapping(
        load_component_yaml(component_id, "component.manual.yaml").get("component")
    )
    return scalar_text(component.get("title"), component_id)


def item_title(items: Sequence[Mapping[str, object]], item_id: str) -> str:
    return scalar_text(item_by_id(items, item_id).get("title"), item_id)


def component_data_profile(component_id: str, data_id: str) -> Mapping[str, object]:
    return item_by_id(component_data_profiles(component_id), data_id)


def component_evidences(component_id: str) -> Mapping[str, Mapping[str, object]]:
    content = load_component_yaml(component_id, "evidences.manual.yaml")
    return {
        evidence_id: evidence
        for item in as_sequence(content.get("evidences"))
        for evidence in [as_mapping(item)]
        for evidence_id in [evidence.get("id")]
        if isinstance(evidence_id, str)
    }


def component_bindings(component_id: str) -> Sequence[Mapping[str, object]]:
    content = load_component_yaml(component_id, "bindings.manual.yaml")
    return [as_mapping(item) for item in as_sequence(content.get("bindings"))]


def step_description(step_ref: str) -> str:
    if step_ref == "manual_log_query":
        return "運用ログをtraceIdで検索する"
    if not step_ref.startswith("steps/"):
        return step_ref
    step = as_mapping(load_yaml(E2E_SPEC_ROOT / step_ref).get("step"))
    title = scalar_text(step.get("title"), step_ref)
    endpoint = scalar_text(step.get("endpoint"), "")
    return f"{title} ({endpoint})" if endpoint else title


def binding_matches(
    binding: Mapping[str, object],
    *,
    action_id: str,
    state_id: str,
    tags: set[str],
) -> bool:
    when = as_mapping(binding.get("when"))
    if when.get("action") not in (None, action_id):
        return False
    if when.get("state") not in (None, state_id):
        return False
    return string_set(as_mapping(when.get("data_tags")).get("include")) <= tags


def matching_bindings_for_variant(variant: E2eComponentVariant) -> tuple[Mapping[str, object], ...]:
    tags = string_set(component_data_profile(variant.component_id, variant.data_id).get("tags"))
    return tuple(
        binding
        for binding in component_bindings(variant.component_id)
        if binding_matches(
            binding,
            action_id=variant.action_id,
            state_id=variant.state_id,
            tags=tags,
        )
    )


def expand_value(value: str, *, target_case: E2eTargetCase, variant: E2eComponentVariant) -> str:
    """`${case.id}`、`${<dimension>.id|title|defaults.*}` を具体値へ展開する。"""
    expanded = value.replace("${case.id}", target_case.case_id)
    for dimension in TARGET_DIMENSIONS:
        target_id = variant.target(dimension.dimension_id) or dimension.canonical
        prefix = dimension.dimension_id
        expanded = expanded.replace(f"${{{prefix}.id}}", target_id).replace(
            f"${{{prefix}.title}}", target_title(target_id)
        )
        for key, raw_value in target_defaults(target_id).items():
            if isinstance(raw_value, str):
                expanded = expanded.replace(
                    f"${{{prefix}.defaults.{key}}}",
                    raw_value.replace("${case.id}", target_case.case_id),
                )
    return expanded


def format_setting_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    return str(value)


def flatten_settings(
    value: object,
    *,
    prefix: str,
    target_case: E2eTargetCase,
    variant: E2eComponentVariant,
) -> list[tuple[str, str]]:
    if isinstance(value, Mapping):
        rows: list[tuple[str, str]] = []
        for key, child in cast(Mapping[object, object], value).items():
            key_text = str(key)
            rows.extend(
                flatten_settings(
                    child,
                    prefix=f"{prefix}.{key_text}" if prefix else key_text,
                    target_case=target_case,
                    variant=variant,
                )
            )
        return rows
    if isinstance(value, list | tuple):
        sequence_rows: list[tuple[str, str]] = []
        for index, child in enumerate(cast(Sequence[object], value)):
            sequence_rows.extend(
                flatten_settings(
                    child,
                    prefix=f"{prefix}[{index}]",
                    target_case=target_case,
                    variant=variant,
                )
            )
        return sequence_rows
    return [
        (
            prefix,
            expand_value(format_setting_value(value), target_case=target_case, variant=variant),
        )
    ]


def setting_rows_for_variant(
    *,
    target_case: E2eTargetCase,
    variant: E2eComponentVariant,
) -> tuple[tuple[str, str], ...]:
    profile = component_data_profile(variant.component_id, variant.data_id)
    rows: list[tuple[str, str]] = []
    for key in ("request", "expected"):
        section = as_mapping(profile.get(key))
        if section:
            rows.extend(
                flatten_settings(section, prefix=key, target_case=target_case, variant=variant)
            )
    for binding in matching_bindings_for_variant(variant):
        rows.extend(
            flatten_settings(
                as_mapping(binding.get("error_settings")),
                prefix="",
                target_case=target_case,
                variant=variant,
            )
        )
    return tuple(rows)


def target_label(variant: E2eComponentVariant) -> str:
    labels = [target_title(target_id) for _dimension, target_id in variant.targets]
    return " と ".join(labels) if labels else WHOLE_FLOW_LABEL


def concrete_data_label(variant: E2eComponentVariant) -> str:
    """variantの対象Targetとdata profileから、シナリオ向けの具体データ名を返す。"""
    profile = component_data_profile(variant.component_id, variant.data_id)
    data_title = scalar_text(profile.get("title"), variant.data_id)
    target = target_label(variant)
    if profile.get("label_mode") == "target":
        return target if target != WHOLE_FLOW_LABEL else data_title
    label = scalar_text(profile.get("label"), data_title)
    if target != WHOLE_FLOW_LABEL:
        return f"{target} の{label}"
    return data_title


def binding_text(
    variant: E2eComponentVariant,
    key: str,
    *,
    target_case: E2eTargetCase,
) -> str:
    texts = [
        expand_value(text, target_case=target_case, variant=variant)
        for binding in matching_bindings_for_variant(variant)
        for text in [binding.get(key)]
        if isinstance(text, str)
    ]
    return " ".join(texts)


def evidence_details_for_variant(
    *,
    target_case: E2eTargetCase,
    variant: E2eComponentVariant,
) -> tuple[EvidenceDetail, ...]:
    evidence_map = component_evidences(variant.component_id)
    details: list[EvidenceDetail] = []
    for binding in matching_bindings_for_variant(variant):
        for evidence_ref in as_sequence(binding.get("evidences")):
            evidence_id = as_mapping(evidence_ref).get("ref")
            if not isinstance(evidence_id, str) or evidence_id not in evidence_map:
                continue
            evidence = evidence_map[evidence_id]
            collector = as_mapping(evidence.get("collector"))
            details.append(
                EvidenceDetail(
                    title=scalar_text(evidence.get("title")),
                    collector=step_description(scalar_text(collector.get("step"))),
                    ok_condition=expand_value(
                        scalar_text(evidence.get("ok_condition")),
                        target_case=target_case,
                        variant=variant,
                    ),
                    save_as=expand_value(
                        scalar_text(evidence.get("save_as")),
                        target_case=target_case,
                        variant=variant,
                    ),
                )
            )
    return tuple(details)


def operation_steps_for_variant(variant: E2eComponentVariant) -> tuple[str, ...]:
    refs = [
        ref
        for binding in matching_bindings_for_variant(variant)
        for step_ref in as_sequence(binding.get("steps"))
        for ref in [as_mapping(step_ref).get("ref")]
        if isinstance(ref, str)
    ]
    return unique_texts(tuple(step_description(ref) for ref in refs))


def build_scenario_steps(target_case: E2eTargetCase) -> tuple[ScenarioStepDetail, ...]:
    steps: list[ScenarioStepDetail] = []
    for variant_id in target_case.selected_variants:
        variant = parse_variant(variant_id)
        component_id = variant.component_id
        steps.append(
            ScenarioStepDetail(
                component_title=component_title(component_id),
                action_title=item_title(component_actions(component_id), variant.action_id),
                state_title=item_title(component_states(component_id), variant.state_id),
                data_label=concrete_data_label(variant),
                target_label=target_label(variant),
                operation_steps=operation_steps_for_variant(variant),
                setting_rows=setting_rows_for_variant(target_case=target_case, variant=variant),
                failure_trigger=binding_text(variant, "failure_trigger", target_case=target_case),
                procedure=binding_text(variant, "procedure", target_case=target_case),
                evidences=evidence_details_for_variant(target_case=target_case, variant=variant),
            )
        )
    return tuple(steps)


def render_step_detail(index: int, step: ScenarioStepDetail) -> list[str]:
    operation_text = "、".join(step.operation_steps) if step.operation_steps else step.action_title
    setting_lines = ["| 項目 | 値 |", "|---|---|"]
    if step.setting_rows:
        setting_lines.extend(
            f"| `{markdown_escape(key)}` | `{markdown_escape(value)}` |"
            for key, value in step.setting_rows
        )
    else:
        setting_lines.append("| - | 設定値なし |")
    evidence_lines = [
        (
            f"- {markdown_escape(evidence.title)}。取得方法は"
            f"{markdown_escape(evidence.collector)}。"
            f"確認条件は{markdown_escape(sentence_body(evidence.ok_condition))}。"
            f"保存名は `{evidence.save_as}`。"
        )
        for evidence in step.evidences
    ] or ["- この Step で保存するエビデンスは定義されていない。"]
    return [
        f"### Step {index}: {markdown_escape(step.action_title)}",
        "",
        "#### 目的",
        "",
        (
            f"{step.target_label} に対して {step.component_title} の"
            f"「{markdown_escape(step.action_title)}」を実行し、"
            f"「{markdown_escape(step.state_title)}」を確認する。"
        ),
        "",
        "#### 操作",
        "",
        (
            f"{markdown_escape(operation_text)} を実行する。"
            f"対象データは「{markdown_escape(step.data_label)}」を使う。"
        ),
        *(["", f"実行条件として、{markdown_escape(step.procedure)}"] if step.procedure else []),
        *(
            ["", f"失敗を発生させるため、{markdown_escape(step.failure_trigger)}"]
            if step.failure_trigger
            else []
        ),
        "",
        "#### 設定値",
        "",
        *setting_lines,
        "",
        "#### 確認観点",
        "",
        (
            f"この Step では、操作結果が「{markdown_escape(step.state_title)}」として"
            "観測できることを確認する。"
        ),
        "",
        "#### エビデンス",
        "",
        *evidence_lines,
        "",
    ]


def render_target_steps(target_case: E2eTargetCase) -> list[str]:
    lines: list[str] = []
    for index, step in enumerate(build_scenario_steps(target_case), start=1):
        lines.extend(render_step_detail(index, step))
    return lines


def goal_description(target_case: E2eTargetCase) -> str:
    variant = parse_variant(target_case.goal_variant)
    component_id = variant.component_id
    action_title = item_title(component_actions(component_id), variant.action_id)
    state_title = item_title(component_states(component_id), variant.state_id)
    return (
        f"{target_label(variant)} に対して "
        f"{component_title(component_id)} の「{action_title}」を実行し、"
        f"「{state_title}」を「{concrete_data_label(variant)}」で確認する。"
    )


def render_target_scenario_markdown(target_case: E2eTargetCase) -> str:
    description = goal_description(target_case)
    goal = parse_variant(target_case.goal_variant)
    return "\n".join(
        [
            GENERATED_COMMENT,
            "",
            f"# {target_case.case_id} {component_title(goal.component_id)}",
            "",
            "## 1. 対象",
            "",
            description,
            "",
            "## 2. 処理概要",
            "",
            f"このケースでは、{sentence_body(description)}までを一連の E2E 手順として確認する。",
            "",
            "## 3. 処理詳細",
            "",
            "### 前提条件",
            "",
            *render_target_prerequisites(),
            "",
            *render_target_steps(target_case),
            "## 4. 後続確認",
            "",
            *render_target_matrix_assertions(target_case),
            "",
            f"- {target_case.case_id} が生成ケース一覧のシナリオリンクから参照できる。",
            *(f"- {note}" for note in string_list(flow_document().get("closing_notes"))),
            "",
        ]
    )


def rendered_outputs(output_root: Path = Path("docs/spec/50.e2e")) -> Mapping[Path, str]:
    cases_root = output_root / FLOW_ID / "cases"
    return {
        cases_root / target_case.filename: render_target_scenario_markdown(target_case)
        for target_case in TARGET_CASES
    }


def generate(*, check: bool = False, output_root: Path = Path("docs/spec/50.e2e")) -> int:
    rendered = rendered_outputs(output_root)
    if check:
        return check_outputs(rendered)
    write_outputs(rendered)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
